### PR TITLE
Update Bourbon.io with message about deprecation

### PR DESCRIPTION
**Pull request by enatario**
Byyeeeee bourbs

Screenshot 2024-09-13 at 3 14 15 PM
Screenshot 2024-09-13 at 3 14 21 PM

### CODE REVIEW

**Review by stefannibrasil — APPROVED** [review]
Yay! I don't drink alcohol but I do like bubble tea, so here's one to approve this PR 🧋

**Comment by enatario** [comment]
@stefannibrasil if you have a chance, can you look into the failing build? unsure how to fix

**Comment by stefannibrasil** [comment]
@enatario This has been broken in a while, it's not related to the changes here 👀  Since we're deprecating Bourbon, my suggestion is to merge this PR anyway. We can check if after merge the website does not get updated and then come back to this. But it looks like deploying is working because I can see the latest release version in the website, so we should be good.

**Comment by enatario** [comment]
@stefannibrasil okay thank you!!

**Pull request merged**
